services:
  db:
    image: postgres

    environment:
      - POSTGRES_DB=meme
      - POSTGRES_USER=meme
      - POSTGRES_PASSWORD=meme
    expose:
      - 5432
    volumes:
      - db-data:/data/db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge
