services:
  media:
    container_name: backend-media
    build:
      context: ..
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    ports:
      - 8001:8001
    volumes:
      - ..:/app
    networks:
      - media

networks:
  media:
    driver: bridge
